# Generated by Django 3.0 on 2023-12-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('based', '0007_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='based.Tag', verbose_name='Теги'),
        ),
    ]
