# Generated by Django 3.0 on 2023-12-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('based', '0009_auto_20231217_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='based.Tag', verbose_name='Теги'),
        ),
    ]
